Fix: Introducing fixes to run karma-jasmine (#10)
Fix: Setting specFilter directly on Env is deprecated
fix: ERROR: 'DEPRECATION: fit and fdescribe will cause your suite to report an 'incomplete' status in Jasmine 3.0'
fix:  karma-jasmine-html-reporter bug : '"Uncaught TypeError: env.catchExceptions is not a function\nat node_modules...'

Fixin to have version:
"jasmine": "^2.99.0",
"jasmine-core": "^2.99.0"
ts-loader to 3.5.0.